apiVersion: batch/v1
kind: Job
metadata:
  name: orders-mongo-init
spec:
  template:
    spec:
      containers:
      - name: orders-mongo-init
        image: mongo:4.4
        command:
        - /bin/bash
        - -c
        - |
          until mongo --host orders-mongo-srv --eval "print(\"waited for connection\")"
          do
            sleep 2
          done
          mongo --host orders-mongo-srv --eval '
            rs.initiate({
              _id: "rs0",
              members: [{ _id: 0, host: "orders-mongo-srv:27017" }]
            })
          '
      restartPolicy: OnFailure