apiVersion: batch/v1
kind: Job
metadata:
  name: payments-mongo-init
spec:
  template:
    spec:
      containers:
      - name: payments-mongo-init
        image: mongo:4.4
        command:
        - /bin/bash
        - -c
        - |
          until mongo --host payments-mongo-srv --eval "print(\"waited for connection\")"
          do
            sleep 2
          done
          mongo --host payments-mongo-srv --eval '
            rs.initiate({
              _id: "rs0",
              members: [{ _id: 0, host: "payments-mongo-srv:27017" }]
            })
          '
      restartPolicy: OnFailure